version: '3'
services:
  app:
    container_name: dataraction
    restart: always
    env_file: .env
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: dataraction-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"